version: "3"

services:
  odin:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: odin_server
    image: joealisson/odin:latest
    ports:
      - "5001:5001"
    volumes:
      - .:/app
