// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.18.1
// source: odin.proto

package ptypes

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// OdinClient is the client API for Odin service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type OdinClient interface {
	Audit(ctx context.Context, in *AuditRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
}

type odinClient struct {
	cc grpc.ClientConnInterface
}

func NewOdinClient(cc grpc.ClientConnInterface) OdinClient {
	return &odinClient{cc}
}

func (c *odinClient) Audit(ctx context.Context, in *AuditRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, "/odin.Odin/Audit", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// OdinServer is the server API for Odin service.
// All implementations must embed UnimplementedOdinServer
// for forward compatibility
type OdinServer interface {
	Audit(context.Context, *AuditRequest) (*emptypb.Empty, error)
	mustEmbedUnimplementedOdinServer()
}

// UnimplementedOdinServer must be embedded to have forward compatible implementations.
type UnimplementedOdinServer struct {
}

func (UnimplementedOdinServer) Audit(context.Context, *AuditRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Audit not implemented")
}
func (UnimplementedOdinServer) mustEmbedUnimplementedOdinServer() {}

// UnsafeOdinServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to OdinServer will
// result in compilation errors.
type UnsafeOdinServer interface {
	mustEmbedUnimplementedOdinServer()
}

func RegisterOdinServer(s grpc.ServiceRegistrar, srv OdinServer) {
	s.RegisterService(&Odin_ServiceDesc, srv)
}

func _Odin_Audit_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AuditRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OdinServer).Audit(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/odin.Odin/Audit",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OdinServer).Audit(ctx, req.(*AuditRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Odin_ServiceDesc is the grpc.ServiceDesc for Odin service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Odin_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "odin.Odin",
	HandlerType: (*OdinServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Audit",
			Handler:    _Odin_Audit_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "odin.proto",
}
