name: Go

on:
  push:
  pull_request:
    types: [ opened, synchronize, reopened ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.18
        
    - name: Dependencies
      run: go mod tidy 

    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v ./...

    - name: SonarQube Scan
      uses: SonarSource/sonarqube-scan-action@v1.1.0
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}

